# This config is a STUB! This should never be generated.
# Use the default lua config from https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua



$mainMod = SUPER
$terminal = kitty
$fileManager = dolphin
$menu = rofi -show run

#keybinds
bind = $mainMod, Q, exec, $terminal
bind = $mainMod, C, killactive,
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, R, exec, $menu
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
bind = $mainMod, F, fullscreen, 1
bind = $mainMod, G, exec, cliphist list | rofi -dmenu | cliphist decode | wl-copy
bind = , PRINT, exec, grim - | swappy -f -
bind = SHIFT, PRINT, exec, grim -g "$(slurp)" - | swappy -f -
bind = SUPER, TAB, cyclenext,
bind = SUPER_SHIFT, TAB, cyclenext, prev

#monitor script
source = ~/.config/hypr/monitors.conf

#auto launch
exec-once = hyprpaper
exec-once = waybar
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
